Step 4
olenaniemova/Practice pull request #4
Opened 2018-06-11 07:31 UTC by olenaniemova

2018-06-11 11:06 UTC, akhsunna requested changes

2018-06-11 11:06 UTC, akhsunna commented on Step_1/equipment_api/app/models/category_filter.rb
> +class CategoryFilter < ApplicationRecord
в ActiveRecord є асоціація `has_and_belongs_to_many`
допомагає реалізувати зв'язок багато до багатьох без створення моделі для проміжної таблиці
мені цікаво, чи ти не знала про це, чи ти свідомо відмовилась від цього рішення. якщо знала, то чому вирішила не використовувати?

2018-06-11 11:06 UTC, akhsunna commented on Step_1/equipment_api/app/models/item.rb
> +  scope :option, ->(word) { joins(item_options: :filter_option).where(filter_options: { value: word })  }
![image](https://user-images.githubusercontent.com/7620006/41221855-1030eb68-6d6e-11e8-87d2-36a36d7460d4.png)

2018-06-11 11:06 UTC, akhsunna commented on Step_1/equipment_api/app/models/item.rb
> +  scope :option, ->(word) { joins(item_options: :filter_option).where(filter_options: { value: word })  }
отже клієнт може надсилати айдішки опцій, і ми зможемо фільтрувати по них.
чому це краще:
- по числовим шукається швидше, ніж по стрінговим полям
- ключові поля в нас проіндексовані, а тому швидкодія точно буде набагато кращою!

2018-06-11 11:06 UTC, akhsunna commented on Step_1/equipment_api/db/migrate/20180610162339_remove_datetime_from_filters.rb
> +    remove_column :filters, :created_at, :datetime
в міграції, яка створювала таблицю `filters` немає таких полів
https://github.com/olenaniemova/Practice/blob/43210df25c3095ca2cf96d74a480ce77c2346509/Step_1/equipment_api/db/migrate/20180610152108_create_filters.rb#L3
отож ця міграція ерорить

2018-06-11 11:06 UTC, akhsunna commented on Step_1/equipment_api/spec/acceptance/items_spec.rb
> +      do_request
в тебе це вже працює?

2018-06-11 11:06 UTC, akhsunna commented on Step_1/equipment_api/spec/acceptance/items_spec.rb
> +      do_request
я до речі, зробила `bundle update` і цієї помилки немає
тому проблема в версіях

2018-06-12 14:21 UTC, akhsunna requested changes
окей, треба ще трохи поправити
ну і чекаю на закінчені тести для документації

2018-06-12 14:21 UTC, akhsunna commented on Step_1/equipment_api/app/models/category.rb
> +  has_and_belongs_to_many :filters
поки не відповіси чому обрала цей варіант
і коли який варіант на твою думку краще використовувати
не прийму пул реквест :)

2018-06-12 14:21 UTC, akhsunna commented on Step_1/equipment_api/app/models/item.rb
> +  scope :option, ->(id) { joins(:filter_options).where(filter_options: { id: id })  }
фільтрування за категоріями може працювати за тим же принципом. чому не змінила скоп, що знаходиться чуть вище?

https://github.com/olenaniemova/Practice/pull/4#discussion_r194334104

2018-06-12 14:21 UTC, akhsunna commented on Step_1/equipment_api/db/migrate/20180612074951_create_join_table_item_filter_option.rb
> +      # t.index [:item_id, :filter_option_id]
індекси варто розкоментувати

2018-06-12 14:21 UTC, akhsunna commented on Step_1/equipment_api/spec/acceptance/items_spec.rb
> +# RSpec.describe ItemsController, :type => :controller do
це вже можна видаляти

2018-06-12 14:35 UTC, olenaniemova commented on Step_1/equipment_api/app/models/category.rb
> +  has_and_belongs_to_many :filters
Не обрала його раніше, бо проміжна таблиця, трохи збила, типу якщо є таблиця, то має бути і модель. Чому зараз вибрала цей, бо як ти і сказала, модель не завжди потрібна.
Коли проміжна таблиця містить тільки id інших таблиць, які зв'язує, то краще не створювати модель і працювати з has_and_belongs_to_many. Коли в проміжну таблицю крім id потрібно дадати ще якісь поля і працювати з ними, тоді краще створити модель, і працювати через has_many through:

2018-06-12 15:53 UTC, akhsunna commented on Step_1/equipment_api/app/models/category.rb
> +  has_and_belongs_to_many :filters
окей, приймається :)

додам ще, що треба подумати чи в майбутньому можуть з'явитись ще якісь поля в проміжній таблиці. чи потрібні будуть якісь додаткові валідації. 
https://github.com/rubocop-hq/rails-style-guide#has-many-through
в даному випадку я не можу уявити які тут ще поля можуть додатись. 
тому has_and_belongs_to_many тут нормальний варіант

2018-06-12 16:00 UTC, akhsunna approved these changes

2018-06-12 16:00 UTC, akhsunna commented on Step_1/equipment_api/app/models/item.rb
> +  scope :option, ->(id) { joins(:filter_options).where(filter_options: { id: id })  }
все таки прикопаюсь..

круто бути послідовним і дотримуватись якогось стилю. в даному випадку: логіки в найменуваннях.

чому тут з айдішкою?
https://github.com/olenaniemova/Practice/blob/505df954c157aca3cc38c1fd8612bad8de5f4efb/Step_1/equipment_api/app/models/item.rb#L9

а тут без? 
https://github.com/olenaniemova/Practice/blob/505df954c157aca3cc38c1fd8612bad8de5f4efb/Step_1/equipment_api/app/models/item.rb#L10

суть же схожа

2018-06-12 16:00 UTC, akhsunna commented on Step_1/equipment_api/app/models/item.rb
> +  scope :option, ->(id) { joins(:filter_options).where(filter_options: { id: id })  }
в нас зазвичай для фільтрації скоупи називають типу: `by_category` або `by_categories`, `by_option` або `by_options`. типу починаючи з `by_`
це ніби говорить про те, що ми фільтруємо ПО такому-то полю/асоціації

але ти можеш мати свій стиль, як тобі подобається, адже це твій проект
просто раджу тобі все таки його мати і дотримуватися

2018-06-12 17:35 UTC, merged