Step 6
olenaniemova/Practice pull request #6
Opened 2018-06-19 09:06 UTC by olenaniemova

2018-06-25 08:24 UTC, akhsunna requested changes

2018-06-25 08:24 UTC, akhsunna commented on Step_1/equipment_api/app/controllers/items_controller.rb
> +        params[:filter_options].each { |f| @item.add_filter_opion(f) }
а якщо користувач вирішив забрати якусь опцію, відасайнити, то як тоді?

2018-06-25 08:24 UTC, akhsunna commented on Step_1/equipment_api/app/models/item.rb
> +    filter_options << FilterOption.where(id: filter_option_id) if c.empty?
чому тут `where`?

2018-06-25 08:24 UTC, akhsunna commented on Step_1/equipment_api/app/controllers/items_controller.rb
> +        params[:filter_options].each { |f| item.add_filter_opion(f) }
прочитай уважніше які ще є можливості: https://apidock.com/rails/ActiveRecord/Associations/ClassMethods/has_and_belongs_to_many

2018-06-25 14:26 UTC, olenaniemova commented on Step_1/equipment_api/app/models/item.rb
> +    filter_options << FilterOption.where(id: filter_option_id) if c.empty?
вибірка фільтру за id

2018-06-26 09:32 UTC, akhsunna requested changes

2018-06-26 09:32 UTC, akhsunna commented on Step_1/equipment_api/app/models/item.rb
> +    self.filter_option_ids = fo_ids
чому б просто не додати `filter_option_ids` до списку параметрів сюди:
https://github.com/olenaniemova/Practice/blob/1a00b068183efef9bcdfbbacd3bb6f56f7ffc940/Step_1/equipment_api/app/controllers/items_controller.rb#L49

2018-06-26 10:57 UTC, merged